channels:
  - conda-forge
  - defaults
  - r
  - bioconda
dependencies:
  - python=3.6.9
  - python-igraph==0.7.1.post6
  - louvain==0.6.1
  - r-base==3.4.1
  - bioconductor-edger
  - r-snow
  - r-snowfall
  - r-bitops
  - r-catools
  - bioconductor-rsamtools
  - pybigwig
  - phantompeakqualtools==1.2.0
  - pip
  - scipy==1.1.0
  - numba==0.43.0
  - statsmodels==0.9.0
  - numpy==1.16.3
  - scikit-learn==0.20.0
  - pandas==0.24.2
  - pip:
    - coveralls==1.3.0
    - scanpy==1.4
    - paramiko==2.4.2
    - html5lib==1.0.1
    - lxml==4.2.4
    - bs4==0.0.1
    - deeptools==3.2.1
    - SQLAlchemy==1.3.0
    - PyMySQL==0.9.2
    - slackclient==1.2.1
    - asana==0.9.2
    - matplotlib==2.2.3
    - unittest2==1.1.0
    - Jinja2==2.10.1
    - gviz-api==1.9.0
    - xlrd==1.1.0
    - jsonschema==2.6.0
    - seaborn==0.9.0
    - multiqc==1.7
    - bioservices==1.5.2
    - cellbrowser==0.7.7
    - spython
    - request
    - atlassian-python-api==3.14.0
